name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run linting with flake8
        continue-on-error: true
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-line-length=100 --statistics
      
      - name: Check code formatting with black
        continue-on-error: true
        run: |
          pip install black
          black --check --diff .
      
      - name: Check import sorting with isort
        continue-on-error: true
        run: |
          pip install isort
          isort --check-only --diff .
      
      - name: Run type checking with mypy
        continue-on-error: true
        run: |
          pip install mypy
          mypy . --ignore-missing-imports || echo "Type checking completed with warnings"
      
      - name: Run security checks with bandit
        continue-on-error: true
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . || echo "Security scan completed"
      
      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --verbose --cov=. --cov-report=xml --cov-report=term || echo "No tests found"
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
      
      - name: Run addition tests
        run: make test-addition
      
      - name: Run subtraction tests
        run: make test-subtraction
      
      - name: Run multiplication tests
        run: make test-multiplication

